swagger: "2.0"
info:
  description: "书斋API，这是由华中师范大学木犀团队开发的书斋APP"
  
  version: "1.0.0"
  title: "Library"
  
host: "localhost"
basePath: "/api/v1"
tags:
- name: "users"
  description: "用户基本信息"
  
- name: "books"
  description: "书城的基本信息"
- name: "digest"
  description: "书摘的基本信息"
 
schemes:
- https
- http

paths:
  /createuser:
    post:
      tags:
      - "users"
      summary: "注册用户"
      description: "直接输入密码和昵称"
      parameters:
        - name: data
          in: body
          description: "发送数据"
          schema :
            required: 
              - "name"
              - "password"
            properties :
              name : 
                type : "string"
                description : "用户昵称"
              password :
                type : "string"
                description : "用户密码"
      responses:
        "200":
          description: "注册成功"
          schema :
            properties : 
              user_id :
                type: string
        "400":
          description : "参数不全，客户端语法有问题"
        "401":
          description : "用户名或密码错误"
     
  /login:
    post:
      tags :
        - "users"
      summary: "登录"
      description: "需要用户名和密码"
      parameters:
        - name: "data"
          in: "body"
          description: "post data"
          schema :
            required: 
              - name
              - password
            properties :
              name :
                type : string
                description : 用户昵称
              password :
                type : string
                description : 用户密码
      responses:
        "200":
          description: "登录成功"
          schema : 
            properties :
              token :
                type : string
                description : 传一个token保留，token就是昵称
        "400":
          description: "参数不全，客户端语法有问题"
        "401":
          description: "用户名或密码有问题"
      
  /my/{user_id} :
    get:
      tags:
        - "users"
      summary: "用户主页"
      parameters:
        - $ref: "#/parameters/token"
        - name: "user_id"
          in: "path"
          required: true
          type: "string"
      responses :
        "200" : 
          description : "获取成功"
          schema : 
            properties : 
              Picture :
                description : "头像"
                type : "string"
              Motto :
                description : "座右铭"
                type : "string"
              My_digest :
                description : "我的发布"
                type : "string"
              My_books : 
                description : "我的书架"
                type : "string"
        "404" : 
           description : "没有这个资源"
        "401" :
           description : "token 错误，没有权限"
    put:
      tags: 
        - users
      summary : "从我的发布中删除书摘"
      parameters :
        - $ref: "#/parameters/token"
        - name : user_id
          in : path
          required : true
          type : string
      responses :
        200 :
          description : 删除成功
        401 :
          description : token 错误没有权限
          
  
  /my/{user_id}/mybooks :
    get:
      tags:
      - "users"
      summary: "用户主页，我的书架"
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "获取成功"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/user_books"
        "404":
          description: "没有该资源"
    put :
      tags :
      - "users"
      summary : "从书架上删除书本"
      parameters :
        - $ref : "#/parameters/token"
        - name : user_id
          in : path
          required : true
          type : string
        - name : books_id
          in : body
          schema : 
            type : array
            items :
              properties : 
                books_id :
                  type: integer
      responses :
        200 :
          description : 删除成功
        401 :
          description : token错误
            
  /my/{user_id}/set :
    get:
      tags:
      - "users"
      summary: "进入设置界面"
      parameters:
      - name: "user_id"
        in: "path"
        required : true
        type: "string"
      responses:
        "200":
          description: "获取成功"
        "404":
          description: "没有这个资源"

  /my/{user_id}/set/information :
    get :
      tags : 
      - "users"
      summary : "可以获取用户信息"
      parameters :
      - name : "user_id"
        in : "path"
        required : true
        type : "string"
      responses : 
        "200" :
          description : "获取成功"
          schema :
            properties :
              Picture :
                description : "用户头像"
                type : "string"
              name :
                description : "用户昵称"
                type : "string"
              motto :
                description : "用户座右铭"
                type : "string"
        "404" :
          description : "没有该资源"
        "401" :
          description : "错误没有权限"
    put :
      tags : 
        - "users"
      summary : "修改用户的信息"
      parameters :
        - $ref : "#/parameters/token"
        - name : user_id
          in : path
          required : true
          type : string
        - name : data
          in : body
          schema :
            properties :
              user_name :
                type : string
              user_picture :
                type : string
              user_motto :
                type : string
      responses : 
        200 :
          description : "成功"
        401 :
          description : "token错了"
  /my/{user_id}/set/handbook :
    get :
      tags :
      - "users"
      summary : "用户手册"
      parameters : 
      - name : "user_id"
        in :  "path"
        required : true
        type : "string"
      responses :
        "200" :
          description : "获取成功"
          schema : 
            properties : 
              handboos_informantion :
                description : "用户手册信息"
                type : "string"
        "404" :
          description : "没有该资源"
  
  /my/{user_id}/set/Privacy :
    get :
      tags : 
      - "users"
      summary : "隐私政策"
      parameters :
      - name : "user_id"
        in : "path"
        required : true
        type : "string"
      responses :
        "200" :
          description : "获取成功"
          schema :
            properties :
              Privacy_information :
                description : "内容"
                type : "string"
        "404" :
          description : "没有该资源"
          
  /books:
    get:
      tags:
      - books
      summary: "书城主界面"
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/books_information"
        404:
          description: 没有该资源        
  
  /books/ranking:
    get:
      tags:
      - books
      summary: "书城排行界面"
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/books_information"
        404:
          description: 没有该资源
  
  /books/{class_id}:
    get:
      tags:
      - books
      summary: "某一类别的书籍"
      parameters:
        - name: class_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/books_information"
        404:
          description: 没有该资源
    
  /books/searcher :
    post :
      tags : 
      - books 
      parameters :
        - name : data
          in : body
          schema :
            required :
              - words
            properties :
              words : 
                type : string
                description : 用户输入的句子
      responses :
       200 :
        description : 请求成功
        schema : 
          type : array
          items :
            $ref: "#/definitions/books_information"
       404 :
        description : 没有找到资源
    
  /books/{books_id}/choose :
    get :
      tags : 
      - books
      summary : 书籍信息
      parameters :
        - name : books_id
          in : path
          required : true
          type : string 
      responses : 
        200 :
          description : 获取成功
          schema :
            type : string
            items :
             $ref : "#/definitions/books_information"
        404 :
         description : 没有找到这个资源
  
  /books/result/{digest_id} :
    get :
      tags :
      - books
      summary : 书摘信息
      parameters:
        - name : digest_id
          in : path
          required : true
          type : string
      responses : 
        200 :
          description : 获取成功
          schema :
            type : string
            items : 
             $ref : "#/definitions/digest_information"
        404 :
          description : 没有找到这个资源
          
  /books/{books_id}/select :
    post :
      tags :
      - books
      summary : 加入书架
      parameters :
        - name : books_id
          in : path
          required : true
          type : string
      responses : 
        200 :
          description : 加入成功
        401 :
          description : token 错了
  
  /digest/{user_id}/mysummary:
    get:
      tags:
      - digest
      summary: "书摘主界面"
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/user_digest"
        404:
          description: 没有该资源
    
    put: 
      tags: 
        - digest
      summary: "选择是否公开"
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
        - name: summary_id
          in: header
          type: integer
      responses:
        200:
          description: 改变成功
        400:
          description: 参数不全，客户端语法有问题
        401:
          description: 权限不够    
            
    post:
      tags:
      - digest
      summary: "搜索书摘"
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
        - name: data
          in: body
          schema:
            properties:
              words:
                type: string
                description: 搜索内容
      responses: 
        200:
          description: 搜索成功
          schema:
            type: array
            items:
              $ref: "#/definitions/user_digest"
        404:
          description: 没有数据
          
  /summary/{user_id}/{digest_id}:
    get:
      tags:
      - digest
      summary: "个人书摘内容"
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
        - name: digest_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/digest"
        404:
          description: 没有该资源  
    
    put:
      tags:
      - digest
      summary: "编辑书摘"
      description: 在原有书摘内容上进行编辑
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
        - name: digest_id
          in: path
          required: true
          type: integer
        - name: summary_text
          in: body
          description: post summary_text
          schema:
            required:
              - title
              - chapter
              - summary_content
              - thought
            properties:
              title:
                type: string
                description: 书摘标题
              chapter:
                type: string
                description: 章节名称
              summary_content:
                type: string
                description: 书摘内容
              thought:
                type: string
                description: 感想
              public:
                  type: boolean
                  description: 是否公开
      responses: 
        200:
          description: 编辑成功
          schema:
            properties:
              summary_id: 
                type: integer
              time: 
                type: string
        400:
          description: 参数不全,客户端语法有问题
        401:
          description: 权限不够
  
  /digest/creat:
    post: 
      tags: 
        - digest
      summary: "创作书摘"
      parameters:
        - $ref: "#/parameters/token"
        - name: summary_text
          in: body
          schema:
            required:
              - title
              - chapter
              - summary_content
              - thought
            properties:
              title:
                type: string
                description: 书摘标题
              chapter:
                type: string
                description: 章节名称
              summary_content:
                type: string
                description: 书摘内容
              thought:
                type: string
                description: 感想
              public:
                type: boolean
                description: 是否公开
      responses:
        200:
          description: 创建成功
          schema:
            properties:
              summary_id:
                type: string
              time:
                type: string
        400:
          description: 参数不全，客户端语法有问题
        401:
          description: token错了, 权限不够  
          
  /digest/{user_id}/mydigest/classes:
    get:
      tags:
      - digest
      summary: "书摘分类"
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              properties:
                summary_class:
                  type: string
        404:
          description: 没有该资源        
  
  /digest/{user_id}/digest/{class_id}:
    get:
      tags:
      - digest
      summary: "分类下的书摘"
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
        - name: class_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              $ref: "#/definitions/user_digest"
        404:
          description: 没有该资源
          
  /digest/{user_id}/mydigest/classes/edit:
    get:
      tags:
      - digest
      summary: "编辑书摘分类界面"
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: 获取成功
          schema:   
            type: array
            items:
              properties:
                summary_class:
                  type: string
        404:
          description: 没有该资源
          
    post: 
      tags: 
        - digest
      summary: "添加书摘分类"
      parameters:
        - $ref: "#/parameters/token"
        - name: user_id
          in: path
          required: true
          type: integer
        - name: class_text
          in: body
          schema:
            properties:
              class_name:
                type: string
                description: 分类名称
      responses:
        200:
          description: 添加成功
          schema:
            properties:
              class_id:
                type: integer
        400:
          description: 参数不全，客户端语法有问题
        401:
          description: token错了, 权限不够
          
    delete:
      tags: 
        - digest
      summary: 删除书摘类别
      parameters:
        - $ref: "#/parameters/token"
        - name: user_id
          in: path
          required: true
          type: integer
        - name: class_id
          in: header
          type: integer
      responses:
        200:
          description: 删除成功
        400:
          description: 参数不全，客户端语法有问题
        401:
          description: token错了, 权限不够   

          
definitions :
    user_books : 
      description : "一个信息块,可以显示收藏图书的地方"
      required : 
        - user_id
      properties :
        Books_name : 
          type : "string"
         
    books_information :
      description : 一个信息块，显示图书的信息
      required :
        - books_id
      properties : 
        books_name :
          type: string
        books_picture:
          type : string
        books_author :
          type : string
        books_content :
          description : 书本介绍
          type : string
    
    digest_information :
      description : 一个显示书摘信息的信息块
      required :
         - digest_id
      properties :
        digest_name :
          type : string
        digest_content :
          type : string
        digest_time : 
          type : string
        digest_user :
          type : string
          
    user_digest:
      type: object
      properties:
        user_id:
          type: integer
          description: 用户ID
        title:
          type: string
          description: 书摘名称
        date:
          type: string
          description: 日期
    
    digest:
      type: object
      properties:
        user_id:
          type: integer
          description: 用户ID
        title:
          type: string
          description: 书摘名称
        chapter:
          type: string
          description: 章节名称
        summary_content:
          type: string
          description: 摘录内容
        thought:
          type: string
          description: 感想
        date:
          type: string
          description: 日期
          
parameters :
    token :
      name : token
      in : header
      required : true
      type : string