CREATE DATABASE IF NOT EXISTS study;

USE study;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS chooses;
DROP TABLE IF EXISTS summary;
DROP TABLE IF EXISTS book_classes;
DROP TABLE IF EXISTS summary_classes;

CREATE TABLE users (
	user_id BIGINT NOT NULL AUTO_INCREMENT,
	user_name VARCHAR(100) NOT NULL,
	user_password VARCHAR(100) NOT NULL,
	motto TEXT NOT NULL,
	user_picture VARCHAR(100) NOT NULL,
	PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE books (
	book_id BIGINT NOT NULL AUTO_INCREMENT,
	book_name VARCHAR(100) NOT NULL,
	book_auther VARCHAR(100) NOT NULL,
	book_information TEXT NOT NULL,
	book_picture VARCHAR(100) NOT NULL,
	class_id BIGINT NOT NULL,
	click_sum INT NOT NULL,
	PRIMARY KEY (book_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE users_books (
	id BIGINT NOT NULL AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	book_id BIGINT NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE summary (
	id BIGINT NOT NULL AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	book_id BIGINT NOT NULL,
	class_id BIGINT NOT NULL,
	title VARCHAR(100) NOT NULL,
	summary_information TEXT NOT NULL,
	thought TEXT NOT NULL,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	public BOOLEAN NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE book_class (
	class_id BIGINT NOT NULL AUTO_INCREMENT,
	class_name VARCHAR(100) NOT NULL,
	class_picture TEXT NOT NULL,
	book_sum BIGINT NOT NULL,
	PRIMARY KEY (class_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE summary_class (
	class_id BIGINT NOT NULL AUTO_INCREMENT,
	class_name VARCHAR(100) NOT NULL,
	PRIMARY KEY (class_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

